### ISSUE TITLE
SLES 15.1 issue

### ISSUE THREAD

**Issue by eegcl-bugs** [mgerstner/firewalld-rpcbind-helper#1]
I installed firewalld-rpc-helper via zypper on a SLES 15.1 machine. rpm -q python3 gives
python3-3.6.8-3.23.1.x86_64.

Trying to start the static configuration interactively, the script throws the following error: 
firewall-rpc-helper.py --static-config -p nfs-server 
Performing configuration of static ports for nfs-server pattern
WARNING: This process may overwrite custom configuration of service
command line switches in /etc/sysconfig/nfs
Reading current configuration from /etc/sysconfig/nfs.
Exception occured: 'dict_values' object does not support indexing
Traceback (most recent call last):
  File "/usr/bin/firewall-rpc-helper.py", line 933, in <module>
    firewall_rpc.run()
  File "/usr/bin/firewall-rpc-helper.py", line 298, in run
    self.configureStatic()
  File "/usr/bin/firewall-rpc-helper.py", line 573, in configureStatic
    self.processCfgItemForChange
  File "/usr/bin/firewall-rpc-helper.py", line 685, in processCfgLine
    new_line = item_handler(key, val)
  File "/usr/bin/firewall-rpc-helper.py", line 700, in processCfgItemForChange
    port = self.getPortSuggestion(key, port)
  File "/usr/bin/firewall-rpc-helper.py", line 643, in getPortSuggestion
    proto = current.values()[0]
TypeError: 'dict_values' object does not support indexing

**Comment by mgerstner** [comment]
Thank you for the report. I will have a look in a couple of days.

**Comment by mgerstner** [comment]
I can see the bug the source code leading to this. However I'm not quite sure how you ended up in this context. Can you provide me the output of `rpcinfo -p` on your system when this error occurs? Thank you.

**Comment by eegcl-bugs** [comment]
To resolve above described error, I edited the first line of firewall-rpc-helper and to not use python3: !#/usr/bin/python -s then the script worked fine and helped me to configure the static ports of nfs.  when i now edited the file again in !#/usr/bin/python3 -s , it works now. The above error occurs again if all ports are not configured statically, ( the value is e.g. mountd_port=""), then the error is thrown. rpcinfo -p gives 
   program vers proto   port  service
    100000    4   tcp    111  portmapper
    100000    3   tcp    111  portmapper
    100000    2   tcp    111  portmapper
    100000    4   udp    111  portmapper
    100000    3   udp    111  portmapper
    100000    2   udp    111  portmapper
    100004    2   udp  24502  ypserv
    100004    1   udp  24502  ypserv
    100004    2   tcp  24502  ypserv
    100004    1   tcp  24502  ypserv
    100024    1   udp  21002  status
    100024    1   tcp  21002  status
    100009    1   udp  24503  yppasswdd
    100009    1   tcp  24503  yppasswdd
    100005    1   udp  20048  mountd
    100005    1   tcp  20048  mountd
    100005    2   udp  20048  mountd
    100005    2   tcp  20048  mountd
    100005    3   udp  20048  mountd
    100005    3   tcp  20048  mountd
    100003    3   tcp   2049  nfs
    100003    4   tcp   2049  nfs
    100227    3   tcp   2049  nfs_acl
    100003    3   udp   2049  nfs
    100227    3   udp   2049  nfs_acl
    100021    1   udp  21003  nlockmgr
    100021    3   udp  21003  nlockmgr
    100021    4   udp  21003  nlockmgr
    100021    1   tcp  21003  nlockmgr
    100021    3   tcp  21003  nlockmgr
    100021    4   tcp  21003  nlockmgr

**Comment by mgerstner** [comment]
Yeah running with python2 is a workaround. But I still don't see how this code path can be reached given your output. Anyways I will commit a fix for python3.
